/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2016-12-15 15:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jdbc.Jdbc;

public final class guanliyuan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("jdbc.Jdbc");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      jdbc.Jdbc hh = null;
      hh = (jdbc.Jdbc) _jspx_page_context.getAttribute("hh", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (hh == null){
        hh = new jdbc.Jdbc();
        _jspx_page_context.setAttribute("hh", hh, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');

Cookie cookies[]=request.getCookies();
Cookie sCookie=null; 
for(int i=0;i<cookies.length;i++){
sCookie=cookies[i];
if(sCookie!=null){
      if(("cookie").equals(sCookie.getName())){
        if(hh.cheakcookie(sCookie.getValue(),0)){
      out.write("<!DOCTYPE >\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"uft-8\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-3.1.1.min.js\"></script>\n");
      out.write("\t<title>管理员界面</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/guanliyuan.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"top\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<a href=\"#\" class=\"fr\">退出系统</a>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t");
      out.print(hh.getcookieuser(sCookie.getValue()));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<img style=\"position: absolute;\" src=\"img/guanliwelcome.jpg\" />\n");
      out.write("\t\t<div class=\"bianse\" style=\"margin-left: 650px;height: 177px;\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"daohang\">\n");
      out.write("\t\t<center class=\"daoh\">教师信息查询与修改</center>\n");
      out.write("\t\t<center class=\"daoh\">学生信息查询与修改</center>\n");
      out.write("\t\t<center class=\"daoh\">修改密码</center>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"xx\">\n");
      out.write("\t\t<div class=\"bk\">\n");
      out.write("\t\t\t<table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t<caption class=\"title\">\n");
      out.write("\t\t\t\t\t教师信息表\n");
      out.write("\t\t\t\t</caption>\n");
      out.write("\t\t\t\t<colgroup>\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t<col>\n");
      out.write("\t\t\t\t</colgroup>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>工号</td>\n");
      out.write("\t\t\t\t\t\t<td>姓名</td>\n");
      out.write("\t\t\t\t\t\t<td>性别</td>\n");
      out.write("\t\t\t\t\t\t<td>生日</td>\n");
      out.write("\t\t\t\t\t\t<td>入职日期</td>\n");
      out.write("\t\t\t\t\t\t<td>职务</td>\n");
      out.write("\t\t\t\t\t\t<td>政治面貌</td>\n");
      out.write("\t\t\t\t\t\t<td>籍贯</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<div class=\"gundong\">\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t<colgroup>\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col class=\"colw\" width=\"100px\">\n");
      out.write("\t\t\t\t\t\t<col>\n");
      out.write("\t\t\t\t\t</colgroup>\n");
      out.write("\t\t\t\t\t<tbody id=\"dataview\">\n");
      out.write("\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"xxinput canw\" readonly type=\"text\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("                        -->\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<button id=\"xxrefresh\">刷新</button>\n");
      out.write("\t\t\t<button id=\"xxchange\">修改</button>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<script type=\"text/javascript\" src=\"js/allshare.js\" ></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/guanliyuan.js\"></script>");

					return;
        }
      }
   }
}
      out.write("\n");
      out.write("<script>\n");
      out.write("\talert(\"请先登录！\");\n");
      out.write("\twindow.location.href = \"LoginFrom.jsp\";\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
