/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2016-12-15 08:52:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginFrom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE >\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<script src=\"./js/jquery-3.1.1.min.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\t<style>\n");
      out.write("\t\tbody {\n");
      out.write("\t\t\tmin-width: 1200px;\n");
      out.write("\t\t\tmin-height: 580px\n");
      out.write("\t\t}\n");
      out.write("\t\t#div0 {\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\theight: 100%\n");
      out.write("\t\t}\n");
      out.write("\t\t#div1 {\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\theight: 80px;\n");
      out.write("\t\t\tbackground-color: #FFFFAA;\n");
      out.write("\t\t\tborder-top: 1px solid #FFD306;\n");
      out.write("\t\t\tborder-bottom: 1px solid #FFD306;\n");
      out.write("\t\t}\n");
      out.write("\t\t.img1_1 {\n");
      out.write("\t\t\twidth: 200px;\n");
      out.write("\t\t\theight: 60px;\n");
      out.write("\t\t\tmargin: 8px 5%;\n");
      out.write("\t\t}\n");
      out.write("\t\t#div2 {\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\theight: 84%;\n");
      out.write("\t\t}\n");
      out.write("\t\t.div2_1 {\n");
      out.write("\t\t\twidth: 55%;\n");
      out.write("\t\t\theight: 500px;\n");
      out.write("\t\t\tmargin: 1px;\n");
      out.write("\t\t\tfloat: left;\n");
      out.write("\t\t}\n");
      out.write("\t\t.img1_2 {\n");
      out.write("\t\t\twidth: 600px;\n");
      out.write("\t\t\theight: 100px;\n");
      out.write("\t\t\tmargin: 80px 20%\n");
      out.write("\t\t}\n");
      out.write("\t\th1 {\n");
      out.write("\t\t\tmargin: 100px 25%;\n");
      out.write("\t\t}\n");
      out.write("\t\t#p2_1 {\n");
      out.write("\t\t\tfont-size: 15pt;\n");
      out.write("\t\t}\n");
      out.write("\t\t.div2_2 {\n");
      out.write("\t\t\twidth: 44%;\n");
      out.write("\t\t\theight: 500px;\n");
      out.write("\t\t\tmargin: 1px auto;\n");
      out.write("\t\t\tfloat: left;\n");
      out.write("\t\t}\n");
      out.write("\t\t.div2_2_1 {\n");
      out.write("\t\t\twidth: 330;\n");
      out.write("\t\t\theight: 380px;\n");
      out.write("\t\t\tborder: 1px solid #EAC100;\n");
      out.write("\t\t\tmargin: 80px;\n");
      out.write("\t\t\tborder-radius: 5px;\n");
      out.write("\t\t\twebkit-border-radius: 5px;\n");
      out.write("\t\t\tmoz-border-radius: 5px;\n");
      out.write("\t\t}\n");
      out.write("\t\t.a2_1 {\n");
      out.write("\t\t\tpadding: 18px;\n");
      out.write("\t\t\tdisplay: block;\n");
      out.write("\t\t\tbackground-color: #FFFFCE;\n");
      out.write("\t\t\tpadding-left: 120px;\n");
      out.write("\t\t\tborder-bottom: 1px solid #EAC100;\n");
      out.write("\t\t}\n");
      out.write("\t\t.account {\n");
      out.write("\t\t\twidth: 250px;\n");
      out.write("\t\t\theight: 35px;\n");
      out.write("\t\t\tmargin: 0px;\n");
      out.write("\t\t\tfloat: left;\n");
      out.write("\t\t\tborder: 0;\n");
      out.write("\t\t\toutline: none;\n");
      out.write("\t\t\toverflow: hidden\n");
      out.write("\t\t}\n");
      out.write("\t\t.password {\n");
      out.write("\t\t\twidth: 280px;\n");
      out.write("\t\t\theight: 35px;\n");
      out.write("\t\t\tmargin: 0px;\n");
      out.write("\t\t\tborder: 0;\n");
      out.write("\t\t\toutline: none;\n");
      out.write("\t\t\toverflow: hidden\n");
      out.write("\t\t}\n");
      out.write("\t\t.a2_2 {\n");
      out.write("\t\t\tdisplay: block;\n");
      out.write("\t\t\tpadding: 10px 105px;\n");
      out.write("\t\t\tbackground: #FFD306;\n");
      out.write("\t\t\tmargin: 40px;\n");
      out.write("\t\t\tcolor: white;\n");
      out.write("\t\t\tfont-family: 黑体;\n");
      out.write("\t\t\ttext-decoration: none;\n");
      out.write("\t\t\tfont-size: 15pt\n");
      out.write("\t\t}\n");
      out.write("\t\t.t2_1 {\n");
      out.write("\t\t\tposition: relative;\n");
      out.write("\t\t\ttop: -4px\n");
      out.write("\t\t}\n");
      out.write("\t\t.c2_1 {\n");
      out.write("\t\t\tmargin-left: 50px;\n");
      out.write("\t\t\twidth: 20px;\n");
      out.write("\t\t\theight: 20px\n");
      out.write("\t\t}\n");
      out.write("\t\ta.a2_2:hover {\n");
      out.write("\t\t\tbackground: #FFE153;\n");
      out.write("\t\t\ttext-decoration: none\n");
      out.write("\t\t}\n");
      out.write("\t\tli {\n");
      out.write("\t\t\tlist-style-type: none;\n");
      out.write("\t\t\tfloat: left\n");
      out.write("\t\t}\n");
      out.write("\t\tul {\n");
      out.write("\t\t\tmargin-left: 50px\n");
      out.write("\t\t}\n");
      out.write("\t\t.a2_3 {\n");
      out.write("\t\t\tpadding: 5px;\n");
      out.write("\t\t\tdisplay: block;\n");
      out.write("\t\t\tborder-right: 1px solid #EAC100\n");
      out.write("\t\t}\n");
      out.write("\t\ta.a2_3:hover {\n");
      out.write("\t\t\ttext-decoration: underline;\n");
      out.write("\t\t\tcolor: #FFD306\n");
      out.write("\t\t}\n");
      out.write("\t\tfieldset {\n");
      out.write("\t\t\twidth: 280px;\n");
      out.write("\t\t\theight: 35px;\n");
      out.write("\t\t\tpadding: 0px;\n");
      out.write("\t\t\tmargin: 20px 40px 5px 25px;\n");
      out.write("\t\t\tborder-color: #DDDDDD\n");
      out.write("\t\t}\n");
      out.write("\t\tfieldset:hover {\n");
      out.write("\t\t\tborder-color: #D2E9FF\n");
      out.write("\t\t}\n");
      out.write("\t\t#div3 {\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\theight: 40px;\n");
      out.write("\t\t\tborder-top: 1px solid #FFD306;\n");
      out.write("\t\t\tborder-bottom: 1px solid #FFD306;\n");
      out.write("\t\t\tbackground-color: #FFFFAA;\n");
      out.write("\t\t\tclear: both;\n");
      out.write("\t\t}\n");
      out.write("\t\t.btn {\n");
      out.write("\t\t\twidth: 22px;\n");
      out.write("\t\t\theight: 22px;\n");
      out.write("\t\t\tbackground: url(img/x.jpg);\n");
      out.write("\t\t\tborder: 0;\n");
      out.write("\t\t\tmargin: 6px 0;\n");
      out.write("\t\t}\n");
      out.write("\t\t.sl {\n");
      out.write("\t\t\tposition: relative;\n");
      out.write("\t\t\ttop: -4px;\n");
      out.write("\t\t\tleft: 35px\n");
      out.write("\t\t}\n");
      out.write("\t</style>\n");
      out.write("\t<body>\n");
      out.write("\t\t<div id=\"div0\">\n");
      out.write("\t\t\t<div id=\"div1\">\n");
      out.write("\t\t\t\t<img class=\"img1_1\" src=\"img/bgg1.png\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"div2\">\n");
      out.write("\t\t\t\t<div class=\"div2_1\">\n");
      out.write("\t\t\t\t\t<h1>欢迎登陆成绩管理<p id=\"p2_1\">系统</p></h1>\n");
      out.write("\t\t\t\t\t<img class=\"img1_2\" src=\"img/q.png\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"div2_2\">\n");
      out.write("\t\t\t\t\t<div class=\"div2_2_1\">\n");
      out.write("\t\t\t\t\t\t<a class=\"a2_1\">账号密码登录</a>\n");
      out.write("\t\t\t\t\t\t<form action=\"\">\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"account\" type=\"text\" name=\"account\" value=\"\"></input>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" class=\"btn\" value=\"\"></input>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"password\" type=\"password\" name=\"password\" value=\"\"></input>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"c2_1\"></input>\n");
      out.write("\t\t\t\t\t\t<font class=\"t2_1\">记住密码</font>\n");
      out.write("\t\t\t\t\t\t<select class=\"sl\" id=\"Sl\">\n");
      out.write("\t\t\t\t\t\t\t<option>管理员</option>\n");
      out.write("\t\t\t\t\t\t\t<option>教师</option>\n");
      out.write("\t\t\t\t\t\t\t<option>学生</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t<a class=\"a2_2\">登录</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"a2_3\">忘了密码?</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"a2_3\">意见反馈</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"div3\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
      out.write("<script src=\"js/allshare.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("<script src=\"./js/LoginFrom.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
